### ISSUE TITLE
Demo does not provide any result

### ISSUE THREAD

**Issue by karelin** [AymenKallala/RAG_Maestro#1]
Hi there,
Nice idea!
Unfortunately, when I've tried a couple of questions, including "What is LLava?" from Readme, demo does not produce any result :(

**Comment by AymenKallala** [comment]
Hello ! Thank you for letting me know. Bug was fixed. I had to increase the max number of instances, I was not quite expecting this traffic on the app to be honest. You should be able to request again now!
